### PR TITLE
Only clone repos necessary for selected services

### PR DESCRIPTION
**Pull request by fitztrev**
Faster startup times for gitpod workspaces + prevents cloning unnecessary repos

### CODE REVIEW

**Review by trevorbayless — COMMENTED** [review]
From a fresh checkout of this PR (with an empty `repo` directory), I'm seeing an issue where empty directories are being created for services that I did not select. For example, I selected "Berserk" as the only optional service I wanted:

Screenshot_20231025_161301

And it mentioned in the output the 5 repos that were necessary to clone. However, in my `repos` directory I have the following that were created:

Screenshot_20231025_161631

In this instance, it additionally created all of the directories in the screenshot above owned by `root`, but they are empty.

This is problematic, because the next time I run `./lila-docker down`, followed by a `start` and let's say I want to select the `scalachess` service this time around, I won't be able to as the directory already exists (and is owned by root):

image

**Comment by fitztrev** [comment]
Thanks for testing! I will work on addressing this.

It's creating those empty folders because they are the volumes defined for the containers in `docker-compose.yml`.

When I tested, it wasn't an issue because on both my Mac and Linux machines, it creates them as my user (not root). So next time I do a `start` and clone a repo I haven't cloned before, it's able to override that folder. Our Docker engines must be configured slightly differently.

**Comment by fitztrev** [comment]
Pushed 2 commits to fix. The first did it in bash but the Rust command had to communicate which dirs to create, so I had to create a new .env var. The second changes that behavior and mounts the `repos` dir to the command's container and creates them directly in Rust.

**Review by trevorbayless — COMMENTED** [review]
Unfortunately, now everything is owned by `root` causing initial cloning to fail:

image

Since I'm only able to recreate this at the moment, I'll take a look on my end to see if I can figure out what's going on.

**Comment by fitztrev** [comment]
I tried it in gitpod and got that error too. Just reverted the 2nd commit and went back to creating it in bash. Now it creates them with the `gitpod` user correctly.

**Review by trevorbayless — APPROVED** [review]
Tested and it's now working for me as well.

**Pull request merged**
